version: '3.4'

services:
    postgres_db:
        container_name: postgresdb
        image: postgres
        environment:
            POSTGRES_USER_FILE: /var/lib/postgresql/config/postgres-user
            POSTGRES_PASSWORD_FILE: /var/lib/postgresql/config/postgres-passwd 
            PGDATA: /var/lib/postgresql/data/pgdata 
        ports:
            - 5433:5432
        restart: on-failure
        volumes:
            - './data:/var/lib/postgresql/data'
            - './postgres/config:/var/lib/postgresql/config'
    
    migrationContainer:
        image: flyway/flyway
        container_name: migrator
        volumes: 
            - ./flyway/sql_versions:/flyway/sql
            - ./flyway/conf:/flyway/conf
        command: -configFiles=/flyway/conf/configuration.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
        depends_on: 
            - postgres_db